# ~/.config/neofetch/config.conf

# ─────────────────────────────────────────────────────────────
# Logo
# ─────────────────────────────────────────────────────────────

image_backend="ascii"
ascii_source="$HOME/.config/fastfetch/wall_ascii.txt"

# Similar visual spacing to fastfetch
gap=4

# Logo colors
ascii_colors=(2 6)


# ─────────────────────────────────────────────────────────────
# Info
# ─────────────────────────────────────────────────────────────

print_info() {
    info title
    info line_break

    info "OS"       os
    info "Kernel"   kernel
    info "Shell"    shell
    info "Term"     term
    info "WM"       wm
    info "Uptime"   uptime
    info "CPU"      cpu
    info "GPU"      gpu
    info "RAM"      memory
    info "Disk"     disk "/"

    info line_break
    info cols
}


# ─────────────────────────────────────────────────────────────
# Colors
# ─────────────────────────────────────────────────────────────

# key / value / title
colors=(2 7 6 7 7 7)

# Key color
bold="on"
