# Dark Red / Black
# ~/.config/btop/themes/dark-red.theme

theme[main_bg]="#080808"
theme[main_fg]="#c8c8c8"
theme[title]="#b84a4a"
theme[hi_fg]="#d85c5c"

theme[selected_bg]="#241010"
theme[selected_fg]="#e6b0b0"

theme[inactive_fg]="#555050"

theme[graph_text]="#a85a5a"
theme[meter_bg]="#171010"

theme[proc_misc]="#8f3f3f"
theme[cpu_box]="#401919"
theme[mem_box]="#341616"
theme[net_box]="#301414"
theme[proc_box]="#281111"

theme[div_line]="#2a1717"

theme[temp_start]="#713838"
theme[temp_mid]="#a44a4a"
theme[temp_end]="#d85c5c"

theme[cpu_start]="#713838"
theme[cpu_mid]="#a44a4a"
theme[cpu_end]="#d85c5c"

theme[free_start]="#493030"
theme[free_mid]="#704040"
theme[free_end]="#965050"

theme[cached_start]="#493030"
theme[cached_mid]="#704040"
theme[cached_end]="#965050"

theme[available_start]="#493030"
theme[available_mid]="#704040"
theme[available_end]="#965050"

theme[used_start]="#713838"
theme[used_mid]="#a44a4a"
theme[used_end]="#d85c5c"

theme[download_start]="#713838"
theme[download_mid]="#a44a4a"
theme[download_end]="#d85c5c"

theme[upload_start]="#713838"
theme[upload_mid]="#a44a4a"
theme[upload_end]="#d85c5c"

theme[process_start]="#713838"
theme[process_mid]="#a44a4a"
theme[process_end]="#d85c5c"
